obj-$(CONFIG_DECON_LCD_S6E3FA0)		+= s6e3fa0_mipi_lcd.o
obj-$(CONFIG_DECON_LCD_S6E3FA2)		+= s6e3fa2_mipi_lcd.o
obj-$(CONFIG_DECON_LCD_S6E8AA0)		+= s6e8aa0_mipi_lcd.o
obj-$(CONFIG_DECON_LCD_S6E3HA0)		+= s6e3ha0_mipi_lcd.o
obj-$(CONFIG_DECON_LCD_S6E3HA0K)	+= s6e3ha0k_mipi_lcd.o
