/* arch/arm/mach-exynos/include/mach/regs-clock-exynos3.h
 *
 * Copyright (c) 2014 Samsung Electronics Co., Ltd.
 * http://www.samsung.com
 *
 * EXYNOS3 - Clock register definitions
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef __ASM_ARCH_REGS_CLOCK_EXYNOS3_H
#define __ASM_ARCH_REGS_CLOCK_EXYNOS3_H __FILE__

#include <plat/cpu.h>
#include <mach/map.h>

#define EXYNOS3_CLK_BUS_TOP_REG(x)      (EXYNOS3_VA_CMU_BUS_TOP + (x))
#define EXYNOS3_CPU_ISP_REG(x)          (EXYNOS3_VA_CMU_CPU_ISP + (x))
#define EXYNOS3_MIF_R_REG(x)            (EXYNOS3_VA_CMU_ACP + (x))
#define EXYNOS3_MIF_L_REG(x)            (EXYNOS3_VA_CMU_DMC + (x))

/*LEFT_BUS */
#define SRC_LEFTBUS			EXYNOS3_CLK_BUS_TOP_REG(0x4200)
#define MUX_STAT_LEFTBUS		EXYNOS3_CLK_BUS_TOP_REG(0x4400)
#define DIV_LEFTBUS			EXYNOS3_CLK_BUS_TOP_REG(0x4500)
#define DIV_STAT_LEFTBUS		EXYNOS3_CLK_BUS_TOP_REG(0x4600)
#define GATE_BUS_LEFTBUS		EXYNOS3_CLK_BUS_TOP_REG(0x4700)
#define GATE_IP_LEFTBUS			EXYNOS3_CLK_BUS_TOP_REG(0x4800)
#define OUT_CMU_LEFTBUS			EXYNOS3_CLK_BUS_TOP_REG(0x4A00)
#define OUT_CMU_LEFTBUS_DIV_STAT	EXYNOS3_CLK_BUS_TOP_REG(0x4A04)

#define SRC_TOP0			EXYNOS3_CLK_BUS_TOP_REG(0xC210)
#define SRC_TOP1			EXYNOS3_CLK_BUS_TOP_REG(0xC214)
#define SRC_G3D				EXYNOS3_CLK_BUS_TOP_REG(0xC22C)
#define SRC_LCD				EXYNOS3_CLK_BUS_TOP_REG(0xC234)
#define SRC_PERIL0			EXYNOS3_CLK_BUS_TOP_REG(0xC250)
#define SRC_PERIL1			EXYNOS3_CLK_BUS_TOP_REG(0xC254)

#define SRC_MASK_LCD			EXYNOS3_CLK_BUS_TOP_REG(0xC334)
#define SRC_MASK_PERIL0			EXYNOS3_CLK_BUS_TOP_REG(0xC350)
#define SRC_MASK_PERIL1			EXYNOS3_CLK_BUS_TOP_REG(0xC354)

#define DIV_TOP				EXYNOS3_CLK_BUS_TOP_REG(0xC510)
#define DIV_G3D				EXYNOS3_CLK_BUS_TOP_REG(0xC52C)
#define DIV_LCD				EXYNOS3_CLK_BUS_TOP_REG(0xC534)
#define DIV_PERIL0			EXYNOS3_CLK_BUS_TOP_REG(0xC550)
#define EXYNOS3_CLKDIV_STAT_LCD		EXYNOS3_CLK_BUS_TOP_REG(0xC634)

#define GATE_BUS_LCD			EXYNOS3_CLK_BUS_TOP_REG(0xC734)
#define GATE_BUS_PERIL			EXYNOS3_CLK_BUS_TOP_REG(0xC750)
#define GATE_SCLK_G3D			EXYNOS3_CLK_BUS_TOP_REG(0xC82C)
#define GATE_SCLK_LCD			EXYNOS3_CLK_BUS_TOP_REG(0xC834)
#define GATE_SCLK_PERIL			EXYNOS3_CLK_BUS_TOP_REG(0xC850)

#define GATE_IP_G3D			EXYNOS3_CLK_BUS_TOP_REG(0xC92C)
#define GATE_IP_LCD			EXYNOS3_CLK_BUS_TOP_REG(0xC934)
#define GATE_IP_PERIL			EXYNOS3_CLK_BUS_TOP_REG(0xC950)
#define SRC_MASK_FSYS			EXYNOS3_CLK_BUS_TOP_REG(0xC340)
#define DIV_FSYS1			EXYNOS3_CLK_BUS_TOP_REG(0xc544)
#define GATE_BUS_FSYS0			EXYNOS3_CLK_BUS_TOP_REG(0xc740)
#define GATE_IP_FSYS			EXYNOS3_CLK_BUS_TOP_REG(0xc940)
#define SRC_FSYS			EXYNOS3_CLK_BUS_TOP_REG(0xc240)
#define GATE_SCLK_FSYS			EXYNOS3_CLK_BUS_TOP_REG(0xC840)

#define EXYNOS3_CLKDIV_GPL_SHIFT		(4)
#define EXYNOS3_CLKDIV_GPL_MASK	\
	(0x7 << EXYNOS3_CLKDIV_GPL_SHIFT)
#define EXYNOS3_CLKDIV_GDL_SHIFT		(0)
#define EXYNOS3_CLKDIV_GDL_MASK	\
	(0xF << EXYNOS3_CLKDIV_GDL_SHIFT)

#define EXYNOS3_CLKDIV_STAT_GPL_SHIFT		(4)
#define EXYNOS3_CLKDIV_STAT_GPL_MASK	\
		(0x1 << EXYNOS3_CLKDIV_STAT_GPL_SHIFT)
#define EXYNOS3_CLKDIV_STAT_GDL_SHIFT		(0)
#define EXYNOS3_CLKDIV_STAT_GDL_MASK	\
	(0x1 << EXYNOS3_CLKDIV_STAT_GDL_SHIFT)

/* RIGHT_BUS */
#define SRC_RIGHTBUS			EXYNOS3_CLK_BUS_TOP_REG(0x8200)
#define EXYNOS3_CLKMUX_STAT_RIGHTBUS	EXYNOS3_CLK_BUS_TOP_REG(0x8400)
#define DIV_RIGHTBUS			EXYNOS3_CLK_BUS_TOP_REG(0x8500)
#define EXYNOS3_CLKDIV_STAT_RIGHTBUS	EXYNOS3_CLK_BUS_TOP_REG(0x8600)
#define EXYNOS3_CLKGATE_BUS_RIGHTBUS	EXYNOS3_CLK_BUS_TOP_REG(0x8700)
#define GATE_BUS_PERIR			EXYNOS3_CLK_BUS_TOP_REG(0x8760)
#define EXYNOS3_CLKGATE_IP_RIGHTBUS	EXYNOS3_CLK_BUS_TOP_REG(0x8800)
#define GATE_IP_PERIR			EXYNOS3_CLK_BUS_TOP_REG(0x8960)
#define EXYNOS3_CLKOUT_CMU_RIGHTBUS	EXYNOS3_CLK_BUS_TOP_REG(0x8A00)
#define EXYNOS3_CLKOUT_CMU_RIGHTBUS_DIV_STAT	EXYNOS3_CLK_BUS_TOP_REG(0x8A04)


#endif
