/* arch/arm/mach-exynos/include/mach/regs-clock-exynos3.h
 *
 * Copyright (c) 2014 Samsung Electronics Co., Ltd.
 *                                                http://www.samsung.com
 *
 * EXYNOS3 - Clock register definitions
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef __ASM_ARCH_REGS_CLOCK_EXYNOS3_H
#define __ASM_ARCH_REGS_CLOCK_EXYNOS3_H __FILE__

#include <plat/cpu.h>
#include <mach/map.h>

#define EXYNOS3_CLK_BUS_TOP_REG(x)      (EXYNOS3_VA_CMU_BUS_TOP + (x)) /* 0x1003_0000*/
#define EXYNOS3_CPU_ISP_REG(x)          (EXYNOS3_VA_CMU_CPU_ISP + (x))     /* 0x1004_0000 */
#define EXYNOS3_MIF_R_REG(x)            (EXYNOS3_VA_CMU_ACP + (x)) 	    /* 0x1045_0000 */
#define EXYNOS3_MIF_L_REG(x)            (EXYNOS3_VA_CMU_DMC + (x))         /* 0x105c_0000 */

/*LEFT_BUS */
#define EXYNOS3_CLKSRC_LEFTBUS                  EXYNOS3_CLK_BUS_TOP_REG(0x4200)
#define EXYNOS3_CLKMUX_STAT_LEFTBUS             EXYNOS3_CLK_BUS_TOP_REG(0x4400)
#define EXYNOS3_CLKDIV_LEFTBUS                  EXYNOS3_CLK_BUS_TOP_REG(0x4500)
#define EXYNOS3_CLKDIV_STAT_LEFTBUS             EXYNOS3_CLK_BUS_TOP_REG(0x4600)
#define EXYNOS3_CLKGATE_BUS_LEFTBUS             EXYNOS3_CLK_BUS_TOP_REG(0x4700)
#define EXYNOS3_CLKGATE_IP_LEFTBUS              EXYNOS3_CLK_BUS_TOP_REG(0x4800)
#define EXYNOS3_CLKOUT_CMU_LEFTBUS              EXYNOS3_CLK_BUS_TOP_REG(0x4A00)
#define EXYNOS3_CLKOUT_CMU_LEFTBUS_DIV_STAT     EXYNOS3_CLK_BUS_TOP_REG(0x4A04)

#define EXYNOS3_CLKSRC_TOP0			EXYNOS3_CLK_BUS_TOP_REG(0xC210)
#define EXYNOS3_CLKSRC_LCD			EXYNOS3_CLK_BUS_TOP_REG(0xC234)
#define EXYNOS3_CLKSRC_PERIL0                   EXYNOS3_CLK_BUS_TOP_REG(0xC250)
#define EXYNOS3_CLKSRC_PERIL1                   EXYNOS3_CLK_BUS_TOP_REG(0xC254)

#define EXYNOS3_CLKSRC_MASK_LCD 		EXYNOS3_CLK_BUS_TOP_REG(0xC334)
#define EXYNOS3_CLKSRC_MASK_PERIL0              EXYNOS3_CLK_BUS_TOP_REG(0xC350)
#define EXYNOS3_CLKSRC_MASK_PERIL1              EXYNOS3_CLK_BUS_TOP_REG(0xC354)

#define EXYNOS3_CLKDIV_TOP			EXYNOS3_CLK_BUS_TOP_REG(0xC510)
#define EXYNOS3_CLKDIV_LCD			EXYNOS3_CLK_BUS_TOP_REG(0xC534)
#define EXYNOS3_CLKDIV_PERIL0			EXYNOS3_CLK_BUS_TOP_REG(0xC550)
#define EXYNOS3_CLKDIV_STAT_LCD 		EXYNOS3_CLK_BUS_TOP_REG(0xC634)

#define EXYNOS3_CLKGATE_BUS_LCD 		EXYNOS3_CLK_BUS_TOP_REG(0xC734)
#define EXYNOS3_CLKGATE_BUS_PERIL		EXYNOS3_CLK_BUS_TOP_REG(0xC750)
#define EXYNOS3_CLKGATE_SCLK_LCD        	EXYNOS3_CLK_BUS_TOP_REG(0xC834)

#define EXYNOS3_CLKGATE_IP_LCD          	EXYNOS3_CLK_BUS_TOP_REG(0xC934)
#define EXYNOS3_CLKGATE_IP_PERIL		EXYNOS3_CLK_BUS_TOP_REG(0xC950)

#define EXYNOS3_CLKDIV_GPL_SHIFT		(4)
#define EXYNOS3_CLKDIV_GPL_MASK	\
	(0x7 << EXYNOS3_CLKDIV_GPL_SHIFT)
#define EXYNOS3_CLKDIV_GDL_SHIFT		(0)
#define EXYNOS3_CLKDIV_GDL_MASK	\
	(0xF << EXYNOS3_CLKDIV_GDL_SHIFT)

#define EXYNOS3_CLKDIV_STAT_GPL_SHIFT		(4)
#define EXYNOS3_CLKDIV_STAT_GPL_MASK	\
		(0x1 << EXYNOS3_CLKDIV_STAT_GPL_SHIFT)
#define EXYNOS3_CLKDIV_STAT_GDL_SHIFT		(0)
#define EXYNOS3_CLKDIV_STAT_GDL_MASK	\
	(0x1 << EXYNOS3_CLKDIV_STAT_GDL_SHIFT)

/* RIGHT_BUS */
#define EXYNOS3_CLKSRC_RIGHTBUS                 EXYNOS3_CLK_BUS_TOP_REG(0x8200)
#define EXYNOS3_CLKMUX_STAT_RIGHTBUS            EXYNOS3_CLK_BUS_TOP_REG(0x8400)
#define EXYNOS3_CLKDIV_RIGHTBUS                 EXYNOS3_CLK_BUS_TOP_REG(0x8500)
#define EXYNOS3_CLKDIV_STAT_RIGHTBUS            EXYNOS3_CLK_BUS_TOP_REG(0x8600)
#define EXYNOS3_CLKGATE_BUS_RIGHTBUS            EXYNOS3_CLK_BUS_TOP_REG(0x8700)
#define EXYNOS3_CLKGATE_BUS_PERIR               EXYNOS3_CLK_BUS_TOP_REG(0x8760)
#define EXYNOS3_CLKGATE_IP_RIGHTBUS             EXYNOS3_CLK_BUS_TOP_REG(0x8800)
#define EXYNOS3_CLKGATE_IP_PERIR                EXYNOS3_CLK_BUS_TOP_REG(0x8960)
#define EXYNOS3_CLKOUT_CMU_RIGHTBUS             EXYNOS3_CLK_BUS_TOP_REG(0x8A00)
#define EXYNOS3_CLKOUT_CMU_RIGHTBUS_DIV_STAT    EXYNOS3_CLK_BUS_TOP_REG(0x8A04)


#endif
