obj-$(CONFIG_DECON_MIPI_DSI)		+= decon_mipi_dsi.o decon_mipi_dsi_lowlevel.o
obj-$(CONFIG_SOC_EXYNOS5430)		+= decon_dt_exynos5430.o decon_pm_exynos5430.o
obj-y					+= decon_fb.o
obj-$(CONFIG_DECON_LCD_S6E3FA0)		+= s6e3fa0_mipi_lcd.o
obj-$(CONFIG_DECON_LCD_S6E8AA0)		+= s6e8aa0_mipi_lcd.o
