obj-$(CONFIG_EXYNOS_MEDIA_DEVICE)	+= mdev/
obj-$(CONFIG_VIDEO_EXYNOS_GSCALER)	+= gsc/
obj-$(CONFIG_VIDEO_EXYNOS_MFC)		+= mfc/
obj-$(CONFIG_VIDEO_EXYNOS_HEVC)		+= hevc/
obj-$(CONFIG_VIDEO_EXYNOS5_FIMC_IS)	+= fimc-is/
EXTRA_CLAGS += -Idrivers/media/video
