obj-$(CONFIG_MULTI_SENSORS)	+= MultiSensors.o MSensorsDrv_fw_update.o
obj-$(CONFIG_SUBCPU_VIBRATOR)	+= subcpu_vibrator.o
obj-$(CONFIG_SUBCPU_BATTERY)	+= subcpu_battery.o
obj-$(CONFIG_TAI_BLUETOOTH) += board-tai-bluetooth.o
obj-$(CONFIG_TAI_GPS)	+= board-tai-gps.o
obj-$(CONFIG_TAI_WIFI) += board-tai-wifi.o
