obj-$(CONFIG_MULTI_SENSORS)	+= MultiSensors.o MSensorsDrv_fw_update.o
obj-$(CONFIG_SUBCPU_VIBRATOR)	+= subcpu_vibrator.o
obj-$(CONFIG_SUBCPU_BATTERY)	+= subcpu_battery.o
obj-$(CONFIG_KINGYO_BLUETOOTH) += board-kingyo-bluetooth.o
obj-$(CONFIG_KINGYO_GPS)	+= board-kingyo-gps.o
