obj-$(CONFIG_MULTI_SENSORS)	+= MultiSensors.o MSensorsDrv_fw_update.o
obj-$(CONFIG_SUBCPU_VIBRATOR)	+= subcpu_vibrator.o
obj-$(CONFIG_SUBCPU_BATTERY)	+= subcpu_battery.o
obj-$(CONFIG_MEDAKA_BLUETOOTH) += board-medaka-bluetooth.o
obj-$(CONFIG_MEDAKA_GPS)	+= board-medaka-gps.o
obj-$(CONFIG_MEDAKA_WIFI) += board-medaka-wifi.o
