dtb-$(CONFIG_ARCH_EXYNOS7) += exynos7-espresso.dtb

dtb-$(CONFIG_SOC_EXYNOS8890) += exynos8890-maestro.dtb
dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-smdk8895.dtb
dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-universal8895.dtb
dtb-$(CONFIG_SOC_EMULATOR8895) += emulator8895-emulator8895.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
